apiVersion: v1
kind: Service
metadata:
  namespace: minecraft
  name: minecraft
spec:
  clusterIP: 10.43.136.0
  clusterIPs:
  - 10.43.136.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mc
    nodePort: 30065
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft
  sessionAffinity: None
  type: NodePort
